version: '3.8'
services:
  db:
    image: postgres:13.2
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafioFrexco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@2021
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      DB_NAME: desafioFrexco
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres2021
    command: yarn start
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - backend
  